Added archived field to Task model
code-corps/code-corps-api pull request #1019
Opened 2017-10-06 06:55 UTC by vishaldeepak

# What's in this PR?
Added Archived field to Tasks

Fixes #1006

2017-10-06 16:45 UTC, JoshSmith commented
Hey @vishaldeepak I know this wasn't in the task, but can you add this to the `TaskView` and `TaskViewTest` so we can be sure it's emitted to the front-end? Make sure they're alpha-ordered.

2017-10-06 16:47 UTC, joshsmith requested changes
Quick change, and see comment above.

2017-10-06 16:47 UTC, JoshSmith commented on lib/code_corps/model/task.ex
> +    |> cast(params, [:status, :archived])
Can you reorder this to be in alpha order?

2017-10-06 16:47 UTC, JoshSmith commented on test/lib/code_corps/model/task_test.exs
> +    end
Solid test here. 👍

2017-10-08 03:41 UTC, vishaldeepak commented
Made changes accordingly

2017-10-08 15:14 UTC, joshsmith submitted a review, later dismissed

2017-10-08 15:16 UTC, joshsmith submitted a review, later dismissed

2017-10-08 15:20 UTC, joshsmith approved these changes

2017-10-08 15:33 UTC, merged