Implement user context logger plug
code-corps/code-corps-api pull request #1101
Opened 2017-10-22 11:24 UTC by teerawat1992

# What's in this PR?

- Create `CodeCorpsWeb.Plug.SetTimberUserContext` plug module.
- Remove unused code from `CodeCorpsWeb.GuardianSerializer` module.
- Apply `CodeCorpsWeb.Plug.SetTimberUserContext` module to:
  - Router file in `:current_user` pipeline.
  - TokenController in `refresh/2` function.

## References
Fixes #932

2017-11-12 19:44 UTC, JoshSmith commented
@begedin would you mind giving this a look?

2017-12-05 09:41 UTC, begedin submitted a review, later dismissed
Well tested and more explicit than what we have. Looks good to me.

2017-12-05 14:25 UTC, joshsmith commented
There are some conflicts here now, though. We've upgraded Guardian.

@teerawat1992 is it possible for you to deconflict the changes and bring them into the newly updated Guardian code?

2017-12-08 15:30 UTC, teerawat1992 commented
@joshsmith Sure, I'll deconflict the changes 🙇

2017-12-08 16:22 UTC, teerawat1992 commented
@joshsmith @begedin I've rebased from develop branch and refactored `Guardian` module, please review again when you guys have time 🙇

2017-12-09 08:01 UTC, begedin requested changes
Once the typo is cleared, I'm fine with merging this in.

2017-12-09 08:01 UTC, begedin commented on test/lib/code_corps/model/user_test.exs
> +    test "returns full name correclty" do
got a typo here, sorry 😬

2017-12-09 14:42 UTC, teerawat1992 commented on test/lib/code_corps/model/user_test.exs
> +    test "returns full name correclty" do
whoops 😅

2017-12-11 07:10 UTC, begedin approved these changes

2017-12-11 07:12 UTC, merged

2017-12-11 19:38 UTC, joshsmith commented
🙌  great work @teerawat1992!