Cleaned up unsupported and ignored event handling
code-corps/code-corps-api pull request #1185
Opened 2017-11-13 13:15 UTC by begedin

This PR deals with us storing partially unsupported (we support the type, but not the action) events as errored. 

Instead, they are now stored as "unsupported".

Additionally, this PR adds `{"pull_request", "syncronized"}` to the list of unsupported events.

While all this works and removes some noise from our _event log_, I should not that functionally, these partially supported events are no different than events we outright ignore. Once and if we add full support, we will not be digging through our event log to restore them, se we should either

- store all events and mark those unsupported as unsupported
- store only fully supported events

The first gives us the benefit of tracking down events we may have missed potentially. The second gives us les work and less things to store, so I'm not sure of our approach (mainly due to not being sure how much we would end up storing).

2017-11-13 13:18 UTC, begedin commented on lib/code_corps/github/event/installation/installation.ex
> -                    {:error, :unexpected_action} |
`:not_yet_implemented` and `:unexpected_action` are no longer reachable with the other changes, so I've removed them for the benefit of simplifying. They would technically still be reachable through a unit test, but not through any sort of integration test.

2017-11-13 13:18 UTC, begedin commented on lib/code_corps/github/webhook/handler.ex
>    end
Removed what's basically an `if` from this module and simply _flattened it out_ from the POV of the controller. Keeps things simpler, allows us to test more directly, and peels off an abstraction layer.

2017-11-13 13:18 UTC, begedin commented on lib/code_corps/github/webhook/processor.ex
> -end
It's basically just a delegate, so no real need for it.

2017-11-13 13:18 UTC, begedin commented on lib/code_corps_web/controllers/github_event_controller.ex
> +        Processor.process(fn -> Handler.handle_supported(type, delivery_id, payload) end)
This is the `CodeCorps.Processor` now, calling `CodeCorps.GitHub.Webhook.Handler` directly

2017-11-13 22:05 UTC, joshsmith approved these changes

2017-11-13 22:12 UTC, joshsmith requested changes
Actually this is not good to go without a migration that takes all `GithubEvent` records where the `failure_reason` is `not_fully_implemented` or `unexpected_action` and nullifies the `failure_reason` and sets `status` to `unsupported`.

2017-11-13 22:14 UTC, joshsmith requested changes

2017-11-13 22:14 UTC, JoshSmith commented on lib/code_corps/github/webhook/event_support.ex
> +    {"pull_request", "synchronized"},
This is actually called `synchronize` and not `synchronized`.

2017-11-14 01:17 UTC, joshsmith submitted a review, later dismissed

2017-11-14 02:05 UTC, JoshSmith commented
There were actually a number of things amiss here, including most importantly that the `GithubEventController` was not responding to unsupported events correctly and our tests were giving false confidence that this was not an issue.

2017-11-14 02:14 UTC, merged