[WIP]Tests for GitHub.Sync.installation_event/1
code-corps/code-corps-api pull request #1380
Opened 2018-02-28 12:37 UTC by zacck

# What's in this PR?

Adding test coverage for the GitHub.Sync.installation_event/1

## References
Fixes #1373 

Progress on: #

2018-02-28 19:29 UTC, zacck commented
Struggling to test some validation clauses, however, seeking some help testing for the following clauses
```
{:error, :validating_github_issue, Changeset.t()}
{:error, :validating_user, Changeset.t()}
{:error, :multiple_issue_users_match}
```

2018-03-13 11:23 UTC, begedin requested changes
Just some extra stuff you forgot to remove and then it's good to merge. 👍

2018-03-13 11:23 UTC, begedin commented on test/lib/code_corps/github/sync/sync_test.exs
> +  end
You probably meant to remove this part.

2018-03-16 16:08 UTC, zacck commented on test/lib/code_corps/github/sync/sync_test.exs
> +  end
haha yes I did

2018-03-16 16:09 UTC, zacck commented
Ok done!!

2018-03-16 16:37 UTC, zacck commented
✂️  done!

2018-03-24 08:25 UTC, begedin approved these changes

2018-03-24 08:25 UTC, merged

2018-03-24 08:25 UTC, begedin commented
@zacck As usual, thank you for your time, work and expertise. 👍