Added a test for comment view
code-corps/code-corps-api pull request #247
Opened 2016-09-21 21:12 UTC by pt-arvind

https://github.com/code-corps/code-corps-api/issues/242

Checking vs CI to see if the tests run OK. Should be 336 total tests with this one.

2016-09-22 15:26 UTC, begedin commented on test/views/comment_view_test.exs
> +                    type: "post"}
Nitpicky, I know, but we actually prefer the following format:

```
data: %{
  id: comment.post_id |> Integer.to_string,
  type: "post"
}

2016-09-22 15:27 UTC, begedin approved these changes
Almost perfect. Just a minor thing you could change and then this is good to go.

2016-09-22 15:28 UTC, begedin requested changes
Previous review was accidentally approved. Will re-approve after changes.

2016-09-22 16:04 UTC, JoshSmith commented
@pt-arvind also still want to address why your tests are failing. You could try to find someone in `#code-corps-api` channel on Slack who can pair. I'm a little slammed next two days, unfortunately.

2016-09-25 19:09 UTC, JoshSmith commented
@pt-arvind would you mind looking at this when you get a chance?

2016-09-26 20:30 UTC, pt-arvind commented
yes! I will fix it up tonight

2016-09-26 20:32 UTC, JoshSmith commented
@pt-arvind thank you!

2016-09-26 20:45 UTC, pt-arvind commented on test/views/comment_view_test.exs
> +                    type: "post"}
no worries! I noticed the same style in a couple other tests, would you like me to change those to be what you've described as well?

2016-09-26 21:13 UTC, pt-arvind commented
am aware of the messed up git history here, I will figure it out before I ask for the final review tonight.

2016-09-27 00:01 UTC, JoshSmith commented
@pt-arvind I think it has to do with the way you're handing rebase. That's my best guess. Don't use `merge`. We can pair on this if you'd like.

2016-09-27 03:21 UTC, pt-arvind commented
nuked this branch because I rebased improperly. Real PR is in the link below:

https://github.com/code-corps/code-corps-api/pull/272

2016-09-27 03:21 UTC, closed without merging