Add test for preview view
code-corps/code-corps-api pull request #301
Opened 2016-10-01 14:52 UTC by Le6ow5k1

Fixes #285

2016-10-01 15:22 UTC, JoshSmith commented
@Le6ow5k1 thanks for the PR! Tests are failing for reasons unrelated to your pull. Forks don't have access to our ENV.

In `circle.yml`, can you change:

```yaml
test:
  override:
    - mix test --include requires_env --cover
```

to

```yaml
test:
  override:
    - MIX_ENV=test mix test --include requires_env --cover
```

Push that as a separate commit, if you would? Thanks!

2016-10-01 15:43 UTC, JoshSmith commented
Actually, hold tight on this suggestion for a moment.

2016-10-01 15:49 UTC, Le6ow5k1 commented
Sorry, already pushed. It seems that it needs complete set of env variables.

2016-10-01 15:58 UTC, JoshSmith commented
@Le6ow5k1 it's running the `requires_env` tags, which you don't have on a fork for security reasons in CI.

I'm going to need to circle back to this unfortunately. Today's my wife and my anniversary.

I do think the issue can be resolved not by removing `requires_env` (we _really_ need that on non-fork CIs), but maybe by running some Circle config that works differently on forks.

2016-10-01 16:08 UTC, JoshSmith commented
We could run an if/else check on `CIRCLE_PR_USERNAME ` in the `test` command so that we _only_ run the command if we assume you have the environment (it's not a fork).

2016-10-01 18:26 UTC, JoshSmith commented
@Le6ow5k1 looks like you fixed it! Apologies for the difficulties there. A new package changed some behavior along with our recent change to run those require_envs on CI. We hadn't a fork push since so it wasn't reflected.

2016-10-01 18:31 UTC, sbatson5 commented on circle.yml
> +      if [ ${CIRCLE_PR_USERNAME} ]; then MIX_ENV=test mix test --cover; else MIX_ENV=test mix test --include requires_env --cover; fi
👏 Nice solution! Could we get this as a separate PR?

2016-10-01 18:45 UTC, joshsmith requested changes
Minor changes here. After those will accept and ask you to rebase and squash after that. Then we'll merge!

🎈 Thanks for this.

2016-10-01 18:45 UTC, JoshSmith commented on test/support/factories.ex
> +      markdown: "Bar",
For this part I would make the markdown and body match up. Also, does the factory need the body of it has the markdown? There seem to be inconsistencies with other factories.

2016-10-01 18:45 UTC, JoshSmith commented on test/views/preview_view_test.exs
> +          "updated-at" => preview.updated_at
Would alpha order these.  Need to add this to a style guide.

2016-10-01 18:45 UTC, JoshSmith commented on circle.yml
> +      if [ ${CIRCLE_PR_USERNAME} ]; then MIX_ENV=test mix test --cover; else MIX_ENV=test mix test --include requires_env --cover; fi
This looks great. Can we add a line to docs explaining the change? Think there's à CI section.

2016-10-01 18:58 UTC, SViccari commented on circle.yml
> +      if [ ${CIRCLE_PR_USERNAME} ]; then MIX_ENV=test mix test --cover; else MIX_ENV=test mix test --include requires_env --cover; fi
Out of curiosity, is there a benefit to having `CIRCLE_PR_USERNAME` set for some but not others? Would it be reasonable for the test suite to run the same way for everyone?

2016-10-01 20:49 UTC, JoshSmith commented on circle.yml
> +      if [ ${CIRCLE_PR_USERNAME} ]; then MIX_ENV=test mix test --cover; else MIX_ENV=test mix test --include requires_env --cover; fi
@SViccari the test suite can't run the same way for everyone. See https://circleci.com/docs/fork-pr-builds/#security-implications-of-running-builds-for-pull-requests-from-forks for discussion of security implications of leaking sensitive environment variables.

2016-10-02 06:59 UTC, Le6ow5k1 commented on circle.yml
> +      if [ ${CIRCLE_PR_USERNAME} ]; then MIX_ENV=test mix test --cover; else MIX_ENV=test mix test --include requires_env --cover; fi
i think there is no need for that, hopefully PR will be merged soon

2016-10-02 07:02 UTC, Le6ow5k1 commented on test/support/factories.ex
> +      markdown: "Bar",
you're right only markdown is needed

2016-10-02 16:36 UTC, joshsmith approved these changes

2016-10-02 16:36 UTC, JoshSmith commented
@Le6ow5k1 just squash and rebase when you have a moment, then we'll merge. Thanks!

2016-10-02 17:53 UTC, Le6ow5k1 commented
@JoshSmith 📦

2016-10-02 17:59 UTC, merged

2016-10-02 17:59 UTC, JoshSmith commented
❤️ 🎈 🎉