Add a note about localhost loopback and json api displaying problems
code-corps/code-corps-api pull request #343
Opened 2016-10-10 11:37 UTC by vidmantas

Related to #313 

Any feedback warmly welcomed - I'm not native English speaker and would love to improve my sentences.

2016-10-11 05:48 UTC, joshsmith requested changes
Thanks for doing this! Just some suggestions for how to improve things here. Let me know if you disagree.

2016-10-11 05:48 UTC, JoshSmith commented on docs/INSTALLING.md
> +If your browser does not support localhost loopback (address not found error), please use `http://api.lvh.me:49235/users` address instead (lvh.me resolves itself and all subdomains to your `localhost
I would actually just change L88 to say `http://api.lvh.me:49235/users` with the note that:

> lvh.me resolves itself and all subdomains to your `localhost` accordingly

If someone more advanced wants to use `api.localhost`, then they can without probably much need for fruther explanation.

2016-10-11 05:48 UTC, JoshSmith commented on docs/INSTALLING.md
> +Note: some browsers, e.g. Safari, Firefox, can ask to download file instead of displaying its contents directly. This is [known issue for JSON API](https://github.com/json-api/json-api/issues/1048) a
", e.g. Safari, Firefox, can" => "like Safari and Firefox may"

"This is a"

Also maybe add recommendation to use tools like https://www.getpostman.com/ or https://paw.cloud/

2016-10-11 19:28 UTC, JoshSmith commented
@vidmantas let me know if you need anything. Always in [Slack](http://slack.codecorps.org) if needed.

2016-10-12 09:46 UTC, vidmantas commented
@JoshSmith thanks for help! Could you please take another look to an updated copy?

2016-10-12 12:34 UTC, begedin requested changes
One more minor change. Should also probably rebase, base branch is out of date.

2016-10-12 12:34 UTC, begedin commented on docs/INSTALLING.md
> +Note: some browsers like Safari and Firefox may can ask to download file instead of displaying its contents directly. This is a [known issue for JSON API](https://github.com/json-api/json-api/issues/
you have a "may can ask you to download" here.

2016-10-12 12:38 UTC, vidmantas commented on docs/INSTALLING.md
> +Note: some browsers like Safari and Firefox may can ask to download file instead of displaying its contents directly. This is a [known issue for JSON API](https://github.com/json-api/json-api/issues/
Oups, fixed, thanks for pointing out.

2016-10-12 15:56 UTC, joshsmith approved these changes

2016-10-12 15:57 UTC, JoshSmith commented
@vidmantas looks great! You just need to rebase and squash and you'll be good to go.

2016-10-13 08:42 UTC, vidmantas commented
@JoshSmith rebased, but now CI fails when trying to upload the report: 
```elixir
** (ExCoveralls.ReportUploadError) Failed to upload the report to 'https://coveralls.io' (reason: status_code = 422, body = {"message":"Couldn't find a repository matching this job.","error":true}).
```
Anything I can do in this situation?

2016-10-13 18:46 UTC, JoshSmith commented
@vidmantas I need to fix this. Stand by.

2016-10-13 18:48 UTC, JoshSmith commented
@vidmantas you should be able to `rebase` again and it should work.

2016-10-14 13:15 UTC, vidmantas commented
@JoshSmith worked, thanks!

2016-10-14 13:15 UTC, vidmantas commented
@begedin could you take another look?

2016-10-14 13:56 UTC, begedin requested changes
Almost done. Again, sorry it moves so slowly.

2016-10-14 13:56 UTC, begedin commented on docs/INSTALLING.md
> +Note: some browsers like Safari and Firefox may ask to download file instead of displaying its contents directly. This is a [known issue for JSON API](https://github.com/json-api/json-api/issues/1048
Sorry to be so such a nitpick, but, "...may ask to download **a** file..."

2016-10-14 15:22 UTC, vidmantas commented on docs/INSTALLING.md
> +Note: some browsers like Safari and Firefox may ask to download file instead of displaying its contents directly. This is a [known issue for JSON API](https://github.com/json-api/json-api/issues/1048
@begedin absolutely no problem, fixed ;)

2016-10-14 21:13 UTC, merged

2016-10-14 21:13 UTC, JoshSmith commented
🙌  @vidmantas!