updated api.apib with stripecard
code-corps/code-corps-api pull request #386
Opened 2016-10-24 18:04 UTC by amyschools

Added endpoint and data structures for StripeCard.

2016-10-24 19:35 UTC, joshsmith reviewed
Below are some questions and some suggested changes.

Did you try previewing the generated API Blueprint (at `localhost:8081`? I'm guessing it didn't render correctly due to syntax errors.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> -
Looks like accidental removal of this line.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +#StripeCard
You should have a space between `#` and `StripeCard`.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +This resource identifies the relationship between a StripeCustomer and a StripeCard. A StripeCustomer has many StripeCards and StripeCard belongs to a StripeCustomer.
I wouldn't call this a relationship. This on its own is a resource.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +#StripeCard
Also, it looks like this breaks the alpha ordering convention.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +#StripeCard
You also need to prefix with `Group`.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +## StripeCards [/stripe_cards]
This should be dasherized.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +        +stripe_customer_id(number) - ID of StripeCustomer.
You don't need the `stripe_customer_id` to make a request to this endpoint.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +        + Attributes (Record Not Found Response)
I would also add in the `401` and `403` response since we know that this is authenticated and authorized.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +
Where is the `StripeCard Resource` defined?

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> ++ data(StripeCards Resource)
I think you need a `StripeCard Response` and a `StripeCards Response`. Look at `Categories` as an example here.

2016-10-24 19:35 UTC, JoshSmith commented on blueprint/api.apib
> +    + Attributes (StripeCards Response)
Where is `StripeCards Response` defined?

2016-10-25 00:06 UTC, joshsmith requested changes
Some of these changes should be implemented inside of this PR.

Other comments, though, are simply suggestions for refactorings that could be placed in future issue(s).

2016-10-25 00:06 UTC, joshsmith commented on blueprint/api.apib
> +### List all Stripe Cards [GET]
Would change `Cards` to `cards` here.

2016-10-25 00:06 UTC, joshsmith commented on blueprint/api.apib
> +### Retrieve a Stripe Card [GET]
Also would change to lowercase `card`.

2016-10-25 00:06 UTC, joshsmith commented on blueprint/api.apib
> +    + id (number) - Id of a Stripe card.
It seems like we're inconsistent in other endpoints about whether or not we have an `id` parameter on `GET` requests for the `show` actions. I'm not sure if we should open another issue for this, but we might want to consider it to make everything consistent across our entire documentation.

2016-10-25 00:06 UTC, joshsmith commented on blueprint/api.apib
> +    + Attributes (Forbidden Response)
We might want to consider opening an issue about the security implications of returning a `401` or `403` vs just a `404` to say that the object doesn't exist, so people don't sneak around trying to find extra information about cards in our API somehow.

2016-10-25 00:06 UTC, joshsmith commented on blueprint/api.apib
> +        + `unchecked`
It looks like there's no default value here. Not sure we should specify, but I guess if we don't the assumption should be that there is no default.

2016-10-25 00:06 UTC, joshsmith commented on blueprint/api.apib
> ++ exp_year: `2017` (number)
Is this an `integer` in #377 inside the database schema?

2016-10-25 00:06 UTC, JoshSmith commented on blueprint/api.apib
> ++ exp_year: `2017` (number)
I also don't think this value needs backticks around it if it's just an integer. Not sure, but we should check some of the other examples.

2016-10-25 00:06 UTC, JoshSmith commented on blueprint/api.apib
> +        + data(array[Project Category Resource Identifier])
We definitely missed this `project-categories` inside of here.

2016-10-25 00:06 UTC, JoshSmith commented on blueprint/api.apib
> ++ type: `stripe-customer`
I think there's some inconsistency across our responses here. `id` and `type` should both be required.

Given some of the inconsistencies we're identifying here that stem from this blueprint not being significantly refactored after the changeover from Rails, I think we should open a parent journey issue that contains all of these suggestions for refactoring/fixes. Then we can break off into individual issues where needed.

2016-10-25 18:03 UTC, amyschools commented on blueprint/api.apib
> +    + Attributes (Forbidden Response)
Added an issue for this: #392

I wasn't sure how to reference this comment specifically.

2016-10-25 18:16 UTC, amyschools commented on blueprint/api.apib
> ++ type: `stripe-customer`
Added issue for this: #393

2016-10-26 19:30 UTC, JoshSmith commented
Ignore coveralls here. I don't know why it's saying test coverage went down. Nonsense.

2016-10-26 19:31 UTC, joshsmith approved these changes

2016-10-26 19:31 UTC, JoshSmith commented
I haven't checked if this renders. Does this still render correctly for you?

Good work! 🎉

2016-10-26 19:32 UTC, JoshSmith commented
Before you can merge, you'll need to rebase and squash your commits into one.

Your reworded commit message should probably read something like:

> Add API Blueprint documentation for StripeCard

2016-10-26 19:38 UTC, joshsmith requested changes
Just noticed something I'd missed here previously.

2016-10-26 19:38 UTC, JoshSmith commented on blueprint/api.apib
> ++ name: `John Doe` (string) - Cardholder name
I think this is missing `inserted-at` and `updated-at` timestamps, which actually all objects in our database will have.

2016-10-26 21:27 UTC, amyschools commented
It was rendering earlier when i tried to push it, but won't anymore - I think it might be because of the stripe auth stuff that was added when we rebased?

2016-10-26 21:32 UTC, JoshSmith commented on blueprint/api.apib
> ++ `updated-at`: `2014-07-07T18:01:26.000Z` (string)
Watch the alpha ordering here.

2016-10-26 21:32 UTC, JoshSmith commented on blueprint/api.apib
> -
Looks like accidental deletion here

2016-10-26 21:32 UTC, JoshSmith commented on blueprint/api.apib
> ++ include JSON API Version
I think this is why rendering is failing. Probably should be `Stripe Card` and not `StripeCard`.

2016-10-26 21:33 UTC, JoshSmith commented on blueprint/api.apib
> ++ include JSON API Version
Actually, no. This shouldn't even exist. Not sure what this is doing here.

2016-10-26 21:34 UTC, JoshSmith commented on blueprint/api.apib
> ++ id_from_stripe: `card_18Emd52eZvKYlo2C1s9DYdv8` (required, string)
I actually think these attributes should be dasherized, and surrounded by ` marks.

2016-10-26 21:35 UTC, joshsmith commented on blueprint/api.apib
> +A Stripe card belongs to a Stripe customer.
I think we changed this now in our system to say that it belongs to a user. Belonging to a customer (for us) is some unnecessary complexity.

2016-10-26 21:40 UTC, JoshSmith commented on blueprint/api.apib
> ++ include JSON API Version
This is still why it's failing. Trying to hit a `StripeCard Resource` that doesn't exist.

2016-10-26 22:11 UTC, joshsmith approved these changes

2016-10-26 22:11 UTC, JoshSmith commented
Squash and rebase.

2016-10-27 00:06 UTC, JoshSmith commented on blueprint/api.apib
> +## Stripe Card (object)
We'll need to put these above Stripe plans.

2016-10-27 00:10 UTC, joshsmith approved these changes
Looks pretty good, a couple notes here.

2016-10-27 00:10 UTC, JoshSmith commented on blueprint/api.apib
> +    + data(array[Stripe Card Resource Identifier])
Watch alpha order here.

2016-10-27 00:10 UTC, JoshSmith commented on blueprint/api.apib
> ++ created: `2016-07-08T03:03:51.967Z` (string)
I would write that this is the `created` time from Stripe. Did we do this in #383?

2016-10-27 00:10 UTC, JoshSmith commented
Didn't mean to approve that one. It should have been requested changes.

2016-10-27 00:11 UTC, JoshSmith commented
And that one comment should not be showing as outdated, so make sure you expand that.

2016-10-27 00:19 UTC, amyschools commented on blueprint/api.apib
> +## Stripe Card (object)
is it not showing up in alpha order from the most recent commit?

2016-10-27 00:29 UTC, amyschools commented on blueprint/api.apib
> ++ created: `2016-07-08T03:03:51.967Z` (string)
It looks like the field is just called `created` in 383. But I can add in a comment like with the amount clarifying that it's from stripe. Does that work?

2016-10-27 00:33 UTC, amyschools commented on blueprint/api.apib
> ++ created: `2016-07-08T03:03:51.967Z` (string)
From 383:
`+  * `created` - A timestamp, indicating when the plan was created by Stripe
`
I'll add the comment into this also.

2016-10-27 04:13 UTC, JoshSmith commented on blueprint/api.apib
> +## Stripe Card (object)
It didn't show up for me randomly.

2016-10-27 04:13 UTC, JoshSmith commented
@amyschools looks great, go ahead and squash again!

2016-10-27 16:55 UTC, merged