leverage test helpers for project-skill test
code-corps/code-corps-api pull request #388
Opened 2016-10-25 15:05 UTC by sbatson5

Had a few free minutes so I thought I would take a pass at another controller and update it to leverage some of the test helpers we have and (hopefully) increase the readability.

2016-10-25 15:06 UTC, sbatson5 commented on test/controllers/project_skill_controller_test.exs
>        assert json["data"]["attributes"] == %{}
🤔 Thoughts on adding an `empty_attributes?` helper? That may be overkill 😛

2016-10-25 15:08 UTC, BlakeWilliams approved these changes
Nice, LGTM!

2016-10-25 15:08 UTC, BlakeWilliams commented on test/controllers/project_skill_controller_test.exs
> +      [first_result, second_result | _] = json |> Map.get("data")
Thoughts on `_rest` instead of just `_`?

2016-10-25 15:08 UTC, BlakeWilliams commented on test/controllers/project_skill_controller_test.exs
>        assert json["data"]["attributes"] == %{}
I like the explicitness of `%{}` personally. :)

2016-10-25 16:43 UTC, begedin requested changes

2016-10-25 16:43 UTC, begedin commented on test/controllers/organization_controller_test.exs
> +      assert ids_from_response(response) == [first_org.id, second_org.id]
Just a suggestion, but how about writing an `assert_ids_from_response/2` helper and then rewriting this as 

```elixir
conn
|> get(path)
|> json_response(200)
|> assert_ids_from_response([first_org.id, second_org.id])
```

We already have an `assert_response_id` helper that works similarly.

Thoughts?

2016-10-25 16:43 UTC, begedin commented on test/controllers/project_skill_controller_test.exs
> +        |> assert_jsonapi_relationship("skill", skill.id)
We prefer the style of 

```elixir
data =
  conn
  |> json_response(200)
  |> Map.get("data")
  |> assert_result_id(project_skill.id)
  # etc
```

2016-10-25 16:43 UTC, begedin commented on test/controllers/project_skill_controller_test.exs
>        assert json["data"]["attributes"] == %{}
`|> assert_attributes_equals(%{})` might not be overkill and is just as explicit. Thoughts?

2016-10-25 18:36 UTC, sbatson5 commented
I think I addressed all the comments @begedin. Let me know if this looks good.

2016-10-25 18:36 UTC, sbatson5 commented on test/controllers/project_skill_controller_test.exs
> -  @attrs %{}
It looks like this was unused.

2016-10-26 02:42 UTC, joshsmith approved these changes

2016-10-26 02:43 UTC, JoshSmith commented
👍  just squash and rebase!

2016-10-26 03:04 UTC, sbatson5 commented
rebased and squashed.

2016-10-26 03:06 UTC, merged