Refactor Project Skills Controller Tests with helpers
code-corps/code-corps-api pull request #410
Opened 2016-11-01 18:49 UTC by amyschools

# What's in this PR?

Added helpers from api_case.ex to refactor controller tests. 

## References
Fixes #408

2016-11-01 19:33 UTC, mackenziehicks commented on test/controllers/project_skill_controller_test.exs
> +    test "does not show resource and instead renders 404 when id is nonexistent", %{conn: conn} do
I think on some of the others this is just "renders 404 when id is nonexistent"

2016-11-01 19:33 UTC, mackenziehicks commented on test/controllers/project_skill_controller_test.exs
>        insert(:organization_membership, role: "admin", member: current_user, organization: organization)
could the `role: "admin"` be eliminated by changing the `@tag :authenticated` to  `@tag authenticated: :admin` ? @JoshSmith, I'm not clear about this.

2016-11-01 19:33 UTC, mackenziehicks commented on test/controllers/project_skill_controller_test.exs
> +  @valid_attrs %{}
maybe this should be called `@attrs` since there is not an `@invalid_attrs` ?

2016-11-01 19:33 UTC, mackenziehicks commented on test/controllers/project_skill_controller_test.exs
> -      project_skill = insert(:project_skill)
does this need to stay? or is it unnecessary? Was wondering if it was needed for test above too? @JoshSmith

2016-11-01 19:34 UTC, joshsmith commented on test/controllers/project_skill_controller_test.exs
> -      project_skill = insert(:project_skill)
It's unnecessary in this one (since `request_delete` now handles the `insert` on its own).

2016-11-01 19:36 UTC, mackenziehicks commented on test/controllers/project_skill_controller_test.exs
> +  @valid_attrs %{}
actually kind of confused on what this actually does with the Map.merge since its empty?

2016-11-01 19:37 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
> -      project_skill = insert(:project_skill)
I do worry about the `@tag authenticated: :admin`, though. I think this is too magical and needs some explanation. Been worried about this previously but hadn't mentioned to @begedin.

What we're testing is that it at least hits the policy; the policy test tests the variations that can happen here (site admin, project owner, project admin, etc). So just having a single test here is fine.

2016-11-01 19:37 UTC, joshsmith commented on test/controllers/project_skill_controller_test.exs
> -      project_skill = insert(:project_skill)
I don't think the `insert` is even required on line 89 in that case. The site admin can do whatever they want.

2016-11-01 19:38 UTC, joshsmith commented on test/controllers/project_skill_controller_test.exs
> +    test "does not show resource and instead renders 404 when id is nonexistent", %{conn: conn} do
I would even shorten universally to just `renders 404`.

2016-11-01 19:39 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
>        insert(:organization_membership, role: "admin", member: current_user, organization: organization)
No, in the latter the `admin` is the "site admin".  In the former the admin is the admin role on the organization.

I think we need to open an issue to change `@tag authenticated: :admin` to `@tag authenticated: :site_admin` for more explicitness.

2016-11-01 19:41 UTC, amyschools commented on test/controllers/project_skill_controller_test.exs
>        insert(:organization_membership, role: "admin", member: current_user, organization: organization)
That's what I thought, I think more explicitness would be helpful though.

2016-11-01 19:46 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
> +  @valid_attrs %{}
I think the contrapositive here is again instructive: is `@valid_attrs` useful _at all_?

Seems like you'd be better off assembling the `attrs` as a map, without a `Map.merge` operation, inside the tests where you need those relationships.

2016-11-01 19:49 UTC, mackenziehicks commented on test/controllers/project_skill_controller_test.exs
> +  @valid_attrs %{}
Ok, we actually tried that and noticed the test would pass.  But also noticed in several other tests that `@valid_attrs` and `@invalid_attrs` were set equal to `#{}` so wanted to check before changing it. In some cases, these weren't referenced anywhere else in the tests besides where they were "assigned".  Are these tests that haven't been refactored? Or partially refactored?

2016-11-01 19:52 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
> +  @valid_attrs %{}
It's possible. The churn is so high here that if something has a code smell, it's probably a valid smell.

2016-11-01 20:10 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
> +      assert conn |> request_create(@attrs) |> json_response(422)
This looks like a case where we want `@invalid_attrs`, which is empty (no relationships).

2016-11-01 20:10 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
> +      assert conn |> request_create(@attrs) |> json_response(401)
Do you need to pass in empty attrs here?

2016-11-01 20:10 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
> +      assert conn |> request_create(@attrs) |> json_response(403)
Do you need to pass in empty attrs here?

Is the organization/organization membership above doing anything?

2016-11-01 20:10 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
> +      assert conn |> request_delete(project_skill) |> response(204)
Do we need to specify the `project_skill` here?

2016-11-01 22:04 UTC, amyschools commented
@JoshSmith I can't get this test to pass that you changed during our screencast: 

```
  describe "create" do
    @tag authenticated: :admin
    test "creates and renders resource when data is valid", %{conn: conn} do
      project_skill = build(:project_skill)
      assert conn |> request_create(project_skill) |> json_response(201)
    end
```
the error says "Protocol Enumerable not implemented for %CodeCorps.ProjectSkill..."
Am I missing something?

2016-11-01 22:06 UTC, JoshSmith commented
Do it as an `insert` instead and see if that works.

2016-11-01 22:12 UTC, amyschools commented
Still not working, same error...

2016-11-02 23:57 UTC, joshsmith requested changes

2016-11-02 23:57 UTC, JoshSmith commented on test/controllers/project_skill_controller_test.exs
> +      |> assert_ids_from_response([project_skill_1.id, project_skill_2.id])
Is there no `request_index` variant for filters?

2016-11-02 23:57 UTC, JoshSmith commented on test/controllers/role_skill_controller_test.exs
> +       assert second_result["attributes"] == %{}
It looks like spacing in this whole file was affected somehow.

2016-11-03 16:48 UTC, begedin commented on test/controllers/project_skill_controller_test.exs
> +      |> assert_ids_from_response([project_skill_1.id, project_skill_2.id])
I don't think there is at the moment, but it would not be a bad idea to write one.

2016-11-03 16:49 UTC, begedin submitted a review, later dismissed
Good for me, after a minor change.

2016-11-03 16:49 UTC, begedin commented on test/controllers/project_skill_controller_test.exs
> +      [project_skill_1, project_skill_2] = insert_pair(:project_skill)
You figured out the missing third record, so I'll just link https://github.com/code-corps/code-corps-api/pull/425/files#r86388037 as a pointer on how to write this in one line.

2016-11-03 19:11 UTC, joshsmith requested changes

2016-11-03 19:11 UTC, JoshSmith commented on test/controllers/role_skill_controller_test.exs
> +       assert second_result["attributes"] == %{}
This still needs to be fixed to be mergeable.

2016-11-03 19:28 UTC, amyschools commented on test/controllers/role_skill_controller_test.exs
> +       assert second_result["attributes"] == %{}
Was looking at the wrong file. I think I got it now

2016-11-03 19:40 UTC, joshsmith approved these changes

2016-11-03 19:40 UTC, JoshSmith commented
LGTM.

2016-11-03 22:12 UTC, merged