Refactor Role Skills Controller Tests
code-corps/code-corps-api pull request #416
Opened 2016-11-01 23:28 UTC by amyschools

# What's in this PR?

Adding helpers from api_case.ex.

## References
Fixes #414 

Progress on: #413

2016-11-02 16:55 UTC, sbatson5 approved these changes
This looks good to me 👍. Nice work!

2016-11-02 22:22 UTC, joshsmith requested changes

2016-11-02 22:22 UTC, JoshSmith commented on test/controllers/role_skill_controller_test.exs
> +      assert json_response(conn, 200)["data"] == []
I would keep this roughly as it is in some of the closed PRs. `conn |> get(path) |> json_response(200)`, then assign the response and assert against that.

2016-11-02 22:22 UTC, JoshSmith commented on test/controllers/role_skill_controller_test.exs
>        skill = insert(:skill, title: "test skill")
I don't think you need to the attributes here. Just `insert(:role)` will work.

2016-11-02 23:07 UTC, amyschools commented on test/controllers/role_skill_controller_test.exs
> +      assert json_response(conn, 200)["data"] == []
does this work? i didn't realize there was a request_index function to help with that until just now.
```  
describe "index" do
    test "lists all entries on index", %{conn: conn} do
    [project_skill_1, project_skill_2] = insert_pair(:project_skill)

     conn
     |> request_index
     |> json_response(200)
     |> assert_ids_from_response([project_skill_1.id, project_skill_2.id])
    end
```

2016-11-02 23:08 UTC, JoshSmith commented on test/controllers/role_skill_controller_test.exs
> +      assert json_response(conn, 200)["data"] == []
I didn't realize that either.

2016-11-02 23:58 UTC, joshsmith requested changes

2016-11-02 23:58 UTC, JoshSmith commented on test/controllers/role_skill_controller_test.exs
> +       |> assert_ids_from_response([role_skill_1.id, role_skill_2.id])
Spacing here is weird. There are three spaces.

2016-11-02 23:58 UTC, JoshSmith commented on test/controllers/role_skill_controller_test.exs
> +      |> assert_ids_from_response([role_skill_1.id, role_skill_2.id])
I might use that `request_index` helper instead.

2016-11-03 00:05 UTC, amyschools commented on test/controllers/role_skill_controller_test.exs
> +      |> assert_ids_from_response([role_skill_1.id, role_skill_2.id])
That created identical tests for listing all the entries on the index and filtering the index...hm

2016-11-03 00:12 UTC, amyschools commented on test/controllers/role_skill_controller_test.exs
> +      |> assert_ids_from_response([role_skill_1.id, role_skill_2.id])
The filter test should have a third item that's not included in the ids from response...maybe I should put that back in to test the filtering

2016-11-03 00:19 UTC, JoshSmith commented on test/controllers/role_skill_controller_test.exs
> +      |> assert_ids_from_response([role_skill_1.id, role_skill_2.id])
@amyschools yes, absolutely.

2016-11-03 16:47 UTC, begedin commented on test/controllers/role_skill_controller_test.exs
> +      [role_skill_1, role_skill_2] = insert_pair(:role_skill)
You figured out the missing third record, so I'll just link https://github.com/code-corps/code-corps-api/pull/425/files#r86388037 as a pointer on how to write this in one line.

2016-11-03 17:28 UTC, begedin approved these changes

2016-11-03 19:10 UTC, joshsmith approved these changes

2016-11-03 19:20 UTC, merged