443 refactor user controller tests
code-corps/code-corps-api pull request #449
Opened 2016-11-08 01:07 UTC by mackenziehicks

# What's in this PR?

Added helpers from api_case.ex to the tests for User Controller.

## References
Fixes #443 

Progress on: #413

2016-11-08 14:49 UTC, begedin requested changes

2016-11-08 14:49 UTC, begedin commented on test/controllers/user_controller_test.exs
> +    assert conn |> authenticate(user) |> put(path, params) |> json_response(200)
Got a bad indent here

2016-11-08 18:39 UTC, begedin commented
Tests seem to pass here. What's the reason for "help wanted". Anything I can help with?

2016-11-08 19:49 UTC, sbatson5 reviewed
This is looking good to me 👍

2016-11-08 19:49 UTC, sbatson5 commented on test/controllers/user_controller_test.exs
> +        |> request_index
I think the patter is not to indent here.

2016-11-08 19:49 UTC, sbatson5 commented on test/controllers/user_controller_test.exs
> +      assert json["data"]["attributes"]["email"] == current_user.email
Do we need to assert that the email is serialized correctly?  Does the json_response returning 200 cover us?

2016-11-08 20:04 UTC, JoshSmith commented on test/controllers/user_controller_test.exs
> +      assert json["data"]["attributes"]["email"] == current_user.email
@sbatson5 I initially thought that we did need to test this here, but we do have a way of testing this at the level of the view test. In that test we do `conn = Phoenix.ConnTest.build_conn |> assign(:current_user, auth_user)` in order to check that the user only see their email when authorized.

We can remove that assertion from here then @mackenziehicks. Asserting `200` is sufficient.

2016-11-11 16:40 UTC, begedin approved these changes
👍

2016-11-11 21:32 UTC, merged