Add StripeConnectAccount update endpoint for assigning an external account
code-corps/code-corps-api pull request #583
Opened 2016-12-19 17:35 UTC by begedin

# What's in this PR?

Adds an update endpoint for StripeConnectAccount, which only allows assigning an external account. Everything else is reported as an unauthorized request.

## References
Fixes #572

2016-12-19 18:49 UTC, joshsmith approved these changes

2016-12-19 18:50 UTC, JoshSmith commented
@begedin LGTM

2016-12-19 18:50 UTC, JoshSmith commented
@begedin to be clear, though, this does not fix #572 in its entirety.

2016-12-19 18:51 UTC, JoshSmith commented
We still need to allow for updates to the StripeConnectAccount for all the other changes that can be made from the Ember app, like the personal/business information, identity document, etc.

2016-12-19 18:56 UTC, begedin commented
I would either rewrite the issue description in #572 then, or change it's title and open a new issue. The description makes it seem like only the `external_account` field is supposed to be updatable by it.

I would actually lean against too specific update actions (this one, and the one proposed for attaching a verification document), but the issue description made it seem to me like this is what's required.

2016-12-19 19:08 UTC, JoshSmith commented
Agree wholeheartedly on not having separate update actions, and think we should avoid that here. I'm definitely onboard with that. The only case where they are advisable, I think, is when they kick off complex separate actions that result in hitting Stripe's API at multiple endpoints. That's obviously avoidable here and instead we're listening for the external account solely in a webhook. Single update here, single update to Stripe.

2016-12-19 19:09 UTC, joshsmith requested changes

2016-12-19 19:09 UTC, JoshSmith commented on test/lib/code_corps/stripe_service/stripe_connect_account_service_test.exs
> +  end
Really I think this should just be `update` now, no?

2016-12-19 19:10 UTC, JoshSmith commented
I think the issue for #572 was written incorrectly by me and instead needs to focus on adapting to changes brought into `stripity_stripe` by @SViccari.

2016-12-19 20:09 UTC, begedin commented
This needs more work. The process should be

* update the Stripe API connect account record with `external_account`.
* this will trigger a `account.external_account.created` webhook, handled in #573. Handling the webhook will insert an external account record into our database.
* however, we should update the `stripe_connect_account` record as part of this request immediately, using the response we get from the stripe API. Otherwise, the account creation status fields will not update in time.

2016-12-20 07:41 UTC, JoshSmith commented
@begedin stripity_stripe account update is merged now.

2016-12-20 12:00 UTC, begedin commented
@JoshSmith I'm not seeing any code related to `Stripe.Account.update` in `stripity_stripe`, merged or otherwise.

What did get merged was the rewrite of the conversion process.

I'll start a PR of my own.

2016-12-20 14:13 UTC, begedin commented
@JoshSmith What this does now is:

* controller receives an update request with the parameter "external_account"
* `handle_update` matches against this parameter only. There is a catch-all match that just returns a 403 (we can add in  matchers for document/recipient in other PRs).
* `StripeConnectAccountService.add_external_account` puts this change to the stripe api (new PR for `Account.update`).
* Api replies with a `Stripe.Account` record, which we use to update the local record.

NOTES:

* Right now, a Stripe list object is not handled properly with stripity stripe. Once that happens, we need to do a minor change here.
* I had to modify `StripeTesting.Account` a good amount to allow for updates. Sadly, the `Account` object is complex, so I had to add helpers to build a fixture with nested data. I don't like it, but I couldn't think of a better way.

2016-12-20 17:18 UTC, JoshSmith commented
@begedin can you bring in the new stripity_stripe or rerun the build so it does so?

2016-12-21 15:14 UTC, begedin commented
@JoshSmith stripity_stripe is up to date now.

Regardless of merge order, this is bound to have some conflicts with the other PRs. I recommending merging #588 first, because using that as a baseline will make resolving conflicts easier.

2016-12-21 22:17 UTC, joshsmith approved these changes

2016-12-21 22:31 UTC, merged