Fix StripeConnectAccount
code-corps/code-corps-api pull request #596
Opened 2016-12-31 08:08 UTC by JoshSmith

# What's in this PR?

WIP.

Attempt to fix StripeConnectAccount's update fn to allow for updating.

2016-12-31 11:01 UTC, begedin commented
I did some long overdue fixes here, which we needed due to some of the changes the PR contains

* `MapUtils.keys_to_string` now does a deep transform and also supports lists
* The `json_payload` `ExMachina` strategy has been replaced with a more accurate `build_json_payload` helper.
* Added an `:update` policy for stripe connect account, still needs testing

## Note on replacing strategy

The strategy had several problems. The first one is that it uses the associated record's default view in order to serialize. The problem there is that it wrongly assumes that the attributes we send in a `:create` or an `:update` request is the exact same set we receive back in a `:show`

This is wrong for several records now.

Additionally, it adds **all attributes** defined by the view to the payload. A `PATCH` request by definition should only contain the attributes that are changed. The new helper supports that definition.

2016-12-31 11:21 UTC, begedin commented
Started cleanup of model tests

Added two new helpers, `assert_validation_triggered(changeset, field, type)` and `assert_error_message(changeset, field, message)`. This allows a more generalized approach to checking changeset validation errors so it's a just a matter of replacing the existing assertions with these.

2017-01-01 21:07 UTC, begedin submitted a review, later dismissed
Have a question on one bit of code, but that's about it for now. Took me a while to get through.

2017-01-01 21:07 UTC, begedin commented on lib/code_corps/stripe_service/adapters/stripe_connect_account.ex
> +    remove_read_only_values(attributes, tail)
How does this work? Seems to me like it only returns the result from removing read only values from the final item in the list (after it recursively gets through the tail). Are we missing some chaining here?

2017-01-01 21:07 UTC, begedin commented on lib/code_corps/stripe_service/util.ex
> +  end
Might not be a bad Idea to have a unit test for this specifically. Separate issue might be good enough for now, though.

2017-01-01 21:21 UTC, JoshSmith commented on lib/code_corps/stripe_service/adapters/stripe_connect_account.ex
> +    remove_read_only_values(attributes, tail)
I think we should remove this altogether, actually.

2017-01-01 21:21 UTC, JoshSmith commented on lib/code_corps/stripe_service/util.ex
> +  end
👍 for separate issue.

2017-01-02 08:10 UTC, begedin requested changes
Minor questions. Otherwise seems good to go.

2017-01-02 08:10 UTC, begedin commented on lib/code_corps/stripe_service/stripe_connect_plan.ex
> +      id: "month_project_" <> to_string(project_id),
Did you mean `month_plan_` here or is `_project_` intentional?

2017-01-02 08:10 UTC, begedin commented on lib/code_corps/stripe_service/adapters/stripe_connect_account.ex
> +  @stripe_update_read_only [
Is this still used for something? I tried searching for it through the file but got nothing.

2017-01-02 08:12 UTC, begedin commented on lib/code_corps/stripe_service/stripe_connect_account.ex
> +      _ -> {:error, :unhandled}
We will likely want to sweep through the code at some point and remove these `_ -> unhandled` cases. They basically swallow any unexpected errors in the process. We should explicitly list any failures we support and handle. If anything unexpected fails, we should treat it as a bug. 

This is basically equivalent with us wrapping a huge chunk of code into a `try-catch` that catches any sort of exception.

2017-01-02 09:03 UTC, JoshSmith commented on lib/code_corps/stripe_service/stripe_connect_plan.ex
> +      id: "month_project_" <> to_string(project_id),
@begedin project is intentional since plans are per-project.

2017-01-02 09:08 UTC, begedin approved these changes

2017-01-02 09:24 UTC, merged