Add Policy Tests: Initial set of tests
code-corps/code-corps-api pull request #785
Opened 2017-04-19 03:04 UTC by securingsincity

# What's in this PR?
Adds tests for Policy Helpers

## References
Fixes #734 

Progress on: #

2017-04-19 03:04 UTC, securingsincity commented
Still a WIP but getting the PR started

2017-04-19 12:53 UTC, securingsincity commented
This should be all set.

2017-04-20 05:47 UTC, JoshSmith commented
@securingsincity thanks! I'll take a look at this tomorrow morning.

2017-04-25 06:59 UTC, begedin requested changes
Sorry for the late review. There is just some minor wording we would like to change. The code itself looks great and will be ready to merge as soon as you're done.

2017-04-25 06:59 UTC, begedin commented on test/lib/code_corps/helpers/policy_test.exs
> +    test "returns false if a project is not owned by the user" do
Add a space here.

2017-04-25 06:59 UTC, begedin commented on test/lib/code_corps/helpers/policy_test.exs
> +    test "returns false when Organization owner_id doesn't match User user_id" do
I would reword this one and the other one for organization to 

`"returns false when organization is not owned by user"`
`"returns true when organization is owned by user"`

We want the tests to talk about "what we want the app to do" not "what's implemented".

2017-04-25 06:59 UTC, begedin commented on test/lib/code_corps/helpers/policy_test.exs
> +    test "should return true if the Task user_id and User id match" do
Again, probably word these as 

`"returns true if the user is the author of the task"`
`"returns false if the user is not the author of the task"`

2017-04-25 12:54 UTC, begedin approved these changes
Looks great. Rebase and merge when ready. 👍

2017-04-25 13:56 UTC, securingsincity commented
@begedin should be squashed now. Thanks.

2017-04-25 14:58 UTC, merged