Add github ids for comments, tasks and projects
code-corps/code-corps-api pull request #799
Opened 2017-05-01 23:03 UTC by npendery

# What's in this PR?

Adds github_ids for multiple models

## References
Fixes #798

2017-05-01 23:26 UTC, securingsincity commented
Do we want to include the relevant changeset in this PR?

2017-05-01 23:32 UTC, npendery commented
@securingsincity yeah, wouldn't hurt. have it in my webhooks PR but dont see why not just adding it in this one 👍

2017-05-02 01:27 UTC, securingsincity requested changes

2017-05-02 01:27 UTC, securingsincity commented on web/models/comment.ex
> +  def github_create_changeset(struct, params) do
can you add tests for these changsets as well?

2017-05-02 01:27 UTC, securingsincity commented on web/models/project.ex
> +  def github_create_changeset(struct, params) do
can you add tests for these changsets as well?

2017-05-02 01:27 UTC, securingsincity commented on web/models/task.ex
> +  def github_create_changeset(struct, params) do
can you add tests for these changsets as well?

2017-05-02 08:26 UTC, begedin requested changes
Other than the missing changeset tests, this looks good.

There's a possibility we might need to extract these ids into actual models containing additional github information at some point, but for now, I think this is enough.

2017-05-02 15:09 UTC, npendery commented
All set @begedin

2017-05-02 15:33 UTC, begedin approved these changes

2017-05-02 15:34 UTC, merged