Controller Functionality for Organisation Invite Controller
code-corps/code-corps-api pull request #861
Opened 2017-08-04 11:55 UTC by vishaldeepak

Added controller, controller tests, ability/policy , route paths for organization invite controller along with relevant documentation
Everything is straightforward, code should reflect techniques used in other controllers

2017-08-07 06:39 UTC, begedin requested changes
Not marked for review yet, but just for the sake of not blocking you.

What I see looks great, but we're still missing view and policy tests.

2017-08-08 14:27 UTC, vishaldeepak commented
whoops, overlooked those tests. Changes include whats required

2017-08-09 05:03 UTC, begedin approved these changes

2017-08-09 05:03 UTC, merged

2017-08-09 05:03 UTC, begedin commented
@vishaldeepak Good work!