Send an email when an organiation invite is created
code-corps/code-corps-api pull request #865
Opened 2017-08-16 05:17 UTC by vishaldeepak

# What's in this PR?
#520  - Send email when organization invite is created

- Created a email template, `organization_invite_email.ex` file.
- Added test for `organization_invite_email.ex` file.
- Updated organisation invite controller `create` action to send email
- Updated test of organisation invite controller for testing if email is sent
- Updated the doc for the above change

_A bit of confusion on what the redirect url of the email should be._

2017-08-17 05:51 UTC, JoshSmith commented
This is looking pretty great! I'll need to check it out locally myself but really love the work you're doing here. 💯

2017-08-25 05:02 UTC, vishaldeepak commented
any updates?. Id like to pick up the next  issue 522.

2017-08-30 00:10 UTC, JoshSmith commented
@vishaldeepak will review shortly. Sorry for the wait!

2017-08-30 15:38 UTC, joshsmith requested changes
Hey @vishaldeepak, here are some minor changes I'd like to see. Overall looks really good. I also think we might be missing a plain-text template here.

2017-08-30 15:38 UTC, JoshSmith commented on blueprint/api.apib
> +On successful creation an email is sent to the give `email` address.
"give" => "given"

2017-08-30 15:38 UTC, JoshSmith commented on config/dev.exs
> +  organization_invite_email_template: "123"
In all of these there's a prefix of `postmark_`. We should keep that trend, and alpha-order accordingly.

2017-08-30 15:38 UTC, JoshSmith commented on lib/code_corps/emails/organization_invite_email.ex
> +      |> URI.merge("/organizations/new" <> "?" <> set_params(code, title))
I think that `invites/organization` is going to be better here.

2017-08-30 15:38 UTC, JoshSmith commented on lib/code_corps/emails/organization_invite_email.ex
> +
Weird line break here.

2017-08-30 15:38 UTC, JoshSmith commented on lib/code_corps_web/controllers/organization_invite_controller.ex
> +  alias CodeCorps.{OrganizationInvite, Emails, Mailer}
Would alpha-order these aliases.

2017-08-30 15:38 UTC, JoshSmith commented on test/lib/code_corps_web/controllers/organization_invite_controller_test.exs
> +    # end
These lines look like they can be removed.

2017-08-31 06:11 UTC, vishaldeepak commented
@JoshSmith what did you mean by `missing a plain text template`?

2017-09-13 05:00 UTC, vishaldeepak commented
@JoshSmith Made change, let me know if any other change is required. !!

2017-09-13 17:45 UTC, JoshSmith commented
Do the other emails not have a text-only version? i.e. no HTML?

2017-09-14 04:10 UTC, vishaldeepak commented
@JoshSmith Im guessing these files contain the same text as in the html versions. If that is the case then I'm unable to find any. For example I tried searching for familiar text in `forgot_password.html` but can't find any reoccurrence of the text in any other file.

2017-09-14 06:34 UTC, begedin commented
@JoshSmith While you can specify a text only version of the postmark template, we do not have any reference to those in the code base, only HTML. I'm not sure if they are specified on the postmark API account.

2017-09-15 03:33 UTC, JoshSmith commented
We'll need to verify this, then.

2017-10-04 21:49 UTC, JoshSmith commented
Can you add the following:

- to `config/dev.exs` - `postmark_organization_invite_email_template: 123`
- to `config/staging.exs` - `postmark_organization_invite_email_template: 3442401`
- to `config/prod.exs` - `postmark_organization_invite_email_template: 3441863`

I also realized that `title` is not quite right here. We need to alter the `title` attribute in `OrganizationInvite` to `organization_name`. In the email template, we should also probably be more explicit and change `url` to `invite_url`.

Apologies it took so long to get you this feedback @vishaldeepak.

2017-10-04 21:50 UTC, JoshSmith commented
Also, it turns out that plain text emails are entirely on Postmark right now. I've apparently hand-jammed them there. Perhaps we should open an issue to also track them in plain-text in our repo?

2017-10-06 04:38 UTC, vishaldeepak commented
Made changes, and rebased with develop

2017-10-06 16:55 UTC, joshsmith approved these changes
Looks good. Just a heads up I had meant to change the `title` in the model to `organization_name`. But all good! I've made the changes and we're good to go.

Thanks! 🙌

2017-10-06 16:55 UTC, merged